name: 'Dhall Validator'
description: 'Validate Dhall files'
author: 'jsoref'
branding:
  icon: 'edit-3'
  color: 'blue'
inputs:
  dhall-json-binary:
    description: 'Binary of dhall-json to use'
    default: 'https://github.com/dhall-lang/dhall-haskell/releases/download/$DHALL_HASKELL/dhall-json-$DHALL_JSON-x86_64-linux.tar.bz2'
    required: false
  dhall-haskell-binary:
    description: 'Binary of dhall to use'
    default: 'https://github.com/dhall-lang/dhall-haskell/releases/download/$DHALL_HASKELL/dhall-$DHALL_HASKELL-x86_64-linux.tar.bz2'
  dhall-haskell:
    description: 'Version of dhall-haskell'
    default: '1.42.0'
    required: false
  dhall-json:
    description: 'Version of dhall-to-json'
    default: '1.7.12'
    required: false
  dhall-files:
    description: 'List of dhall files to check'
    required: false
  dhall-file-list:
    description: 'Null delimited file of dhall files to check'
    required: false
  parallel-jobs:
    description: 'Number of CPUs available for running checks'
    required: false
    default: '2'
  retry-failed-files:
    description: 'On fail retry serially (mostly for when parallel jobs run out of memory)'
    required: false
  verbose:
    description: 'Enable verbose logging'
    default: ''
    required: false
  lint:
    description: 'Lint the dhall files'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        DHALL_HASKELL: ${{ inputs.dhall-haskell }}
        DHALL_HASKELL_BINARY: ${{ inputs.dhall-haskell-binary }}
        DHALL_JSON: ${{ inputs.dhall-json }}
        DHALL_JSON_BINARY: ${{ inputs.dhall-json-binary }}
        FILES: ${{ inputs.dhall-files }}
        LIST: ${{ inputs.dhall-file-list }}
        PARALLEL_JOBS: ${{ inputs.parallel-jobs }}
        RETRY_FAILED_FILES: ${{ inputs.retry-failed-files }}
        VERBOSE: ${{ inputs.verbose }}
        LINT: ${{ inputs.lint }}
      run:
        $GITHUB_ACTION_PATH/check.sh
